#!/bin/bash -l
# This is the setup script for the workstation container. Use it to set the stage for your terraform training, demo, or lab.
set -e

# Wait for Instruqt to finish booting the VM
# This is better than doing sleep
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

# Set Terraform Version
TERRAFORM_VERSION="1.1.5"

# Install desired version of Terraform
wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
mv terraform /usr/local/bin/terraform
chmod +x /usr/local/bin/terraform
rm -f terraform_${TERRAFORM_VERSION}_linux_amd64.zip

# Install software
sudo apt update -y

# Clone repo
git clone https://github.com/nickyoung-hashicorp/hashitalks-2022.git

# Set the user's working directory
set-workdir /root/hashitalks-2022/tf

exit 0
